import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import ChatScreen from "../components/ChatScreen";
import ChatSurface from "../components/ChatSurface";

const SContainer = styled.div`
  position: relative;
  width: 100%;
  max-height: 100vh;
  display: flex;
  flex-direction: column;
  padding: 0 2rem;
  overflow-x: auto;
`;

const SStatic = styled.div`
  position: sticky;
  bottom: 8px;
  padding: 0 8px;
`;

const Home: NextPage = () => {
  return (
    <div style={{ position: "relative" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SContainer>
        <ChatScreen />
        <SStatic>
          <ChatSurface />
        </SStatic>
      </SContainer>
    </div>
  );
};

export default Home;
