import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import Text from "../components/Text";

const SContainer = styled.div`
  width: 100%;
  min-height: 100vh;
  display: flex;
  justify-content: space-around;
  align-items: center;
  flex-direction: column;
`;

const STextBox = styled.div`
  display: flex;
  align-items: center;
  flex-direction: column;
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SContainer>
        <img width={300} src="Chat.png" alt="chat" />
        <STextBox>
          <Text
            type="h3"
            style={{ width: "50ch", textAlign: "center", marginBottom: "2rem" }}
          >
            Treally Chat
          </Text>
          <Text style={{ width: "50ch", textAlign: "center" }}>
            Start decentralized chats with your contacts using a messaging
            key added to your Universal Profile.
          </Text>
        </STextBox>
      </SContainer>
    </div>
  );
};

export default Home;
